wip

diff --git a/.github/workflows/e2e_conflicts.yaml b/.github/workflows/e2e_conflicts.yaml
--- a/.github/workflows/e2e_conflicts.yaml
+++ b/.github/workflows/e2e_conflicts.yaml
@@ -120,11 +120,12 @@ jobs:
       - name: Resolve conflict
         id: resolve-conflict
         run: |
-          echo ${{ steps.conflict.outcome }}
+          if [ ${{ steps.conflict.outcome }}  != "failure" ];
+          then 
+            exit 1
+          fi
           
           PYTHONPATH=$(pwd) python3  tests/e2e/migrate.py  --action resolve-conflict --github-token  ${{ secrets.GITHUB_TOKEN }} '${{ steps.configuration.outputs.discourse }}'
-
-          git status
 
           COMMIT_SHA=$(git log | head -n 1 | sed -En "s/commit\ //p")
           echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
@@ -140,24 +141,24 @@ jobs:
           base_branch: "tests/base"
           commit_sha: ${{  steps.resolve-conflict.outputs.commit_sha }}
 
-      - name: Merge Feature Branch
-        id: merge-feature
-        run: |
-          PYTHONPATH=$(pwd) python3  tests/e2e/migrate.py  --action merge-feature --github-token  ${{ secrets.GITHUB_TOKEN }} '${{ steps.configuration.outputs.discourse }}'
-          COMMIT_SHA=$(git log | head -n 1 | sed -En "s/commit\ //p")
-          echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
-
-      - name: Release Feature
-        id: release-feature
-        uses: canonical/upload-charm-docs@wip-e2e-tests
-        with:
-          discourse_host: discourse.charmhub.io
-          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
-          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          base_branch: "tests/base"
-          commit_sha: ${{  steps.merge-feature.outputs.commit_sha }}
-
-      - name: Cleanup
-        run: |
-          PYTHONPATH=$(pwd) python3  tests/e2e/migrate.py  --action cleanup --github-token  ${{ secrets.GITHUB_TOKEN }} '${{ steps.configuration.outputs.discourse }}'
+      # - name: Merge Feature Branch
+      #   id: merge-feature
+      #   run: |
+      #     PYTHONPATH=$(pwd) python3  tests/e2e/migrate.py  --action merge-feature --github-token  ${{ secrets.GITHUB_TOKEN }} '${{ steps.configuration.outputs.discourse }}'
+      #     COMMIT_SHA=$(git log | head -n 1 | sed -En "s/commit\ //p")
+      #     echo "commit_sha=$COMMIT_SHA" >> "$GITHUB_OUTPUT"
+      #
+      # - name: Release Feature
+      #   id: release-feature
+      #   uses: canonical/upload-charm-docs@wip-e2e-tests
+      #   with:
+      #     discourse_host: discourse.charmhub.io
+      #     discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
+      #     discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     base_branch: "tests/base"
+      #     commit_sha: ${{  steps.merge-feature.outputs.commit_sha }}
+      #
+      # - name: Cleanup
+      #   run: |
+      #     PYTHONPATH=$(pwd) python3  tests/e2e/migrate.py  --action cleanup --github-token  ${{ secrets.GITHUB_TOKEN }} '${{ steps.configuration.outputs.discourse }}'
